version: "3"

services:
    client:
        image: nginx
        ports:
            - 8002:80
        volumes:
            - /Volumes/HDD/Develop/gitRepos/test-repo/src:/usr/share/nginx/html # Path fisical in server deploy